version: 0.2

phases:
  install:
    commands:
      - echo "Installing NVM (Node Version Manager)"
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
      - '[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"'
      - echo "Installing Node.js"
      - nvm install 16
      - nvm use 16
      - node -v
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the React app"
      - npm run build
  post_build:
    commands:
      - echo "Build completed. Preparing artifacts for deployment."

artifacts:
  files:
    - 'build/**/*'
  base-directory: build
